import React from "react";
import Back from "../common/back/Back";
const TermsAndConditions=()=> {
  return (
    <>
    <Back title='Terms and Conditions' />
    <div>
      <p>
        Last Updated: November 2025<br></br><br></br>
        <li>
        <ol><b>1. Acceptance of Terms</b><br></br>
        By accessing or using MentalGlow-AI, you agree to these Terms and Conditions.
        If you do not agree, please discontinue use of the platform.</ol><br></br>
        <ol><b>2. Purpose of the Platform</b><br></br>
        MentalGlow-AI is designed as an AI-based mental wellness and research tool.
        It aims to promote mental health awareness and provide preliminary insights — not medical advice.
        The system is for educational and informational use only.</ol><br></br>
        <ol><b>3. Use of Services</b><br></br>
        You agree to:<br></br>
        <ul>●&nbsp;Use the platform responsibly and ethically.</ul>
        <ul>●&nbsp;Avoid submitting harmful, illegal, or misleading content.</ul>
        <ul>●&nbsp;Not attempt to reverse-engineer, copy, or misuse the AI system or backend APIs.</ul></ol><br></br>
        <ol><b>4. No Medical or Professional Advice</b><br></br>
        The insights or results generated by MentalGlow-AI are produced using AI algorithms and do not replace professional evaluation or therapy.
        Always consult a certified mental health professional for diagnosis or treatment.</ol><br></br>
        <ol><b>5. Intellectual Property</b><br></br>
        All content, design, source code, and models within MentalGlow-AI belong to the project developers.
        You may not reproduce, distribute, or modify any material without prior permission.</ol><br></br>
        <ol><b>6. Limitation of Liability</b><br></br>
        The developers of MentalGlow-AI are not liable for:<br></br>
        <ul>●&nbsp;Misinterpretation of AI insights,</ul>
        <ul>●&nbsp;Any emotional or mental outcomes resulting from using the system, or</ul>
        <ul>●&nbsp;Technical issues, data loss, or unavailability of the service.</ul>
        Use of the platform is at your own discretion and risk.</ol><br></br>
        <ol><b>7. Privacy and Data Handling</b><br></br>
        Your use of this platform is also governed by our Privacy Policy.
        Please review it carefully to understand how your data is processed.</ol><br></br>
        <ol><b>8. Modification of Terms</b><br></br>
        We reserve the right to modify or update these Terms at any time.
        Continued use after updates implies acceptance of the new Terms.</ol><br></br>
        <ol><b>9. Termination</b><br></br>
        We may suspend or terminate access to the service without notice if you violate any terms or misuse the platform.</ol><br></br>
        <ol><b>10. Governing Law</b><br></br>
        These Terms are governed by the applicable laws of India, without regard to conflict-of-law principles.
        Any disputes shall be handled under the jurisdiction of courts located in Faridabad, Haryana.</ol><br></br>
        <ol><b>11. Contact</b><br></br>
        For queries, concerns, or academic collaboration:
        mentalglow.ai@gmail.com</ol><br></br>
        </li>
      </p>
    </div>
    </>
  );
}
export default TermsAndConditions